export const FAQ_ITEMS = [
  { q: 'Where do we deliver?', a: 'We deliver to homes, apartments, gated communities, and housing societies across Kattigenahalli and surrounding neighbourhoods in North Bangalore. We also accept bulk orders for schools, hotels, resorts, offices and other institutions — on separate bulk delivery timings. Contact us for bulk enquiries.' },
  { q: 'What time is milk delivered?', a: 'Morning slot: 7AM – 9AM. Evening slot: 5PM – 7PM. We always aim to deliver within your chosen slot. Bulk institutional orders may have different delivery timings.' },
  { q: 'Can I pause my subscription?', a: 'Yes! You can pause delivery for any specific date directly from your dashboard, at least 12 hours in advance. You can also resume anytime.' },
  { q: 'What is the bottle deposit?', a: 'We charge a refundable bottle deposit of ₹200 per bottle. The full deposit is returned when bottles are given back in good condition. Our 500ml trial pack has no deposit required. Choose Direct Delivery mode to skip the deposit — our delivery person collects the bottle right after delivery.' },
  { q: 'How do I pay?', a: 'Your first order can be paid via Cash on Delivery (COD). For subscriptions and subsequent orders, we use a prepaid wallet system — add balance once and enjoy uninterrupted daily delivery without cash hassles!' },
  { q: 'What is the minimum wallet balance?', a: 'Your wallet must maintain a minimum balance of ₹300 for subscriptions to remain active. If your balance is insufficient for the day\'s delivery, your subscription will be automatically deactivated. Top up your wallet in advance to avoid interruptions — we send a low-balance alert email when your balance drops below ₹300.' },
  { q: 'Is the milk pasteurised and safe to drink directly?', a: 'Our milk is farm-fresh and pure, delivered straight from our farm. It is NOT pasteurised — it is raw, natural cow milk. We strongly recommend boiling the milk before consumption for safety. Boiling ensures any harmful bacteria are eliminated while preserving the natural goodness of the milk.' },
  { q: 'Do you take bulk orders?', a: 'Yes! We supply bulk milk to schools, hotels, resorts, hostels, canteens and other institutions. Bulk orders have special pricing and dedicated delivery timings. Please contact us on WhatsApp or call us for bulk order enquiries.' },
  { q: 'How do I install this as an app on my phone?', a: 'On iPhone: Open the website in Safari, tap the Share button (box with arrow) at the bottom, then tap "Add to Home Screen". On Android: Open in Chrome, tap the 3 dots menu, then tap "Add to Home Screen". The app icon will appear on your home screen!' },
  { q: 'Do I need to download an app from Play Store?', a: 'No! Our website works like an app directly from your browser. Just add it to your home screen and it opens instantly like a native app — no Play Store download needed!' },
]
